[package]
name = "mctui"
version = "0.1.0"
authors = ["noituri"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = "1.0.92"
serde_json = "1.0.39"
sha-1 = "0.8.1"
lazy_static = "1.3.0"
uuid = "0.7.4"
failure = "0.1.5"
termion = "1.5.3"
tui = "0.6.0"
#futures-util-preview = "0.3.0-alpha.16"
#futures-preview = "0.3.0-alpha.16"
