[package]
name = "mctui"
version = "0.1.0"
authors = ["noituri"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = "1.0.92"
serde_json = "1.0.39"
sha-1 = "0.8.1"
lazy_static = "1.3.0"
config = "0.9.3"